"""Repository ports (protocols) for application layer."""

from typing import Protocol, Any, Iterable, Optional

class Repository(Protocol):
    def get(self, entity_id: Any) -> Any: ...
    def add(self, entity: Any) -> None: ...
    def remove(self, entity: Any) -> None: ...
    def list(self, **filters: Any) -> Iterable[Any]: ...

class UnitOfWork(Protocol):
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
