"""initial schema

Revision ID: 674e122dac1c
Revises: 
Create Date: 2026-03-13 21:40:13.751694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674e122dac1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounter_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('combatants_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mj_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mj_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('campaign_invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('invited_user_id', sa.Integer(), nullable=True),
    sa.Column('invited_email', sa.String(length=120), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('is_declined', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['invited_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('campaign_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'user_id')
    )
    op.create_table('character_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('character_type', sa.String(length=20), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('visibility_level', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('background_story', sa.Text(), nullable=True),
    sa.Column('character_class', sa.String(length=50), nullable=True),
    sa.Column('race', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('private_notes', sa.Text(), nullable=True),
    sa.Column('hp_max', sa.Integer(), nullable=False),
    sa.Column('ac_base', sa.Integer(), nullable=False),
    sa.Column('initiative_bonus', sa.Integer(), nullable=True),
    sa.Column('force', sa.Integer(), nullable=True),
    sa.Column('dexterite', sa.Integer(), nullable=True),
    sa.Column('constitution', sa.Integer(), nullable=True),
    sa.Column('intelligence', sa.Integer(), nullable=True),
    sa.Column('sagesse', sa.Integer(), nullable=True),
    sa.Column('charisme', sa.Integer(), nullable=True),
    sa.Column('maitrise_force', sa.Boolean(), nullable=True),
    sa.Column('maitrise_dexterite', sa.Boolean(), nullable=True),
    sa.Column('maitrise_constitution', sa.Boolean(), nullable=True),
    sa.Column('maitrise_intelligence', sa.Boolean(), nullable=True),
    sa.Column('maitrise_sagesse', sa.Boolean(), nullable=True),
    sa.Column('maitrise_charisme', sa.Boolean(), nullable=True),
    sa.Column('current_xp', sa.Integer(), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('pdf_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('join_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_rejected', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'user_id')
    )
    op.create_table('story_arc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_sessions', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_campaign_association',
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['character_template.id'], )
    )
    op.create_table('combat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('current_turn', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('story_arc_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('current_turn_start', sa.DateTime(), nullable=True),
    sa.Column('current_round_start', sa.DateTime(), nullable=True),
    sa.Column('has_started', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['story_arc_id'], ['story_arc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combat_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('combat_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('turn_owner_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('turn_duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['combat_id'], ['combat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combatant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('combat_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('hp_max', sa.Integer(), nullable=False),
    sa.Column('hp_current', sa.Integer(), nullable=False),
    sa.Column('temp_hp', sa.Integer(), nullable=True),
    sa.Column('initiative', sa.Integer(), nullable=False),
    sa.Column('ac_base', sa.Integer(), nullable=False),
    sa.Column('ac_bonus', sa.Integer(), nullable=True),
    sa.Column('conditions', sa.String(length=255), nullable=True),
    sa.Column('is_dead', sa.Boolean(), nullable=True),
    sa.Column('has_fled', sa.Boolean(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=True),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['combat_id'], ['combat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xp_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('combat_id', sa.Integer(), nullable=True),
    sa.Column('xp_amount', sa.Integer(), nullable=False),
    sa.Column('xp_source', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level_before', sa.Integer(), nullable=True),
    sa.Column('level_after', sa.Integer(), nullable=True),
    sa.Column('awarded_by', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character_template.id'], ),
    sa.ForeignKeyConstraint(['combat_id'], ['combat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xp_log')
    op.drop_table('combatant')
    op.drop_table('combat_log')
    op.drop_table('combat')
    op.drop_table('character_campaign_association')
    op.drop_table('story_arc')
    op.drop_table('join_request')
    op.drop_table('character_template')
    op.drop_table('campaign_member')
    op.drop_table('campaign_invitation')
    op.drop_table('email_verification')
    op.drop_table('campaign')
    op.drop_table('user')
    op.drop_table('encounter_template')
    # ### end Alembic commands ###
